# Generated by Django 5.1.3 on 2024-11-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(max_length=1000),
        ),
    ]
